#!/usr/bin/env bash
set -euo pipefail

SEQ_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

KAR_ROOT="${KAR_ROOT:-${HOME}/repos/pqrs-org/Karabiner-Elements}"
SEQ_REPO="${SEQ_REPO:-${HOME}/code/seq}"

OUT="${OUT:-${SEQ_ROOT}/out/action_packs}"
KEY_ID="${KEY_ID:-kar_build}"
TTL_MS="${TTL_MS:-600000}"

mkdir -p "${OUT}"

quote_ap() {
  # Single-quote for action-pack script; escape single quotes minimally.
  local s="$1"
  s="${s//\'/\'\\\'\'}"
  printf "'%s'" "$s"
}

if [ ! -d "${KAR_ROOT}/.git" ]; then
  echo "error: KAR_ROOT is not a git repo: ${KAR_ROOT}" >&2
  exit 1
fi
if [ ! -d "${SEQ_REPO}/.git" ]; then
  echo "error: SEQ_REPO is not a git repo: ${SEQ_REPO}" >&2
  exit 1
fi

echo "Generating patches into ${OUT}"
git -C "${KAR_ROOT}" diff HEAD > "${OUT}/karabiner_latency.patch"
git -C "${SEQ_REPO}" diff HEAD > "${OUT}/seq_latency.patch"

KAR_HEAD="$(git -C "${KAR_ROOT}" rev-parse HEAD)"
SEQ_HEAD="$(git -C "${SEQ_REPO}" rev-parse HEAD)"

KAR_UNTRACKED="$(git -C "${KAR_ROOT}" ls-files --others --exclude-standard || true)"
SEQ_UNTRACKED="$(git -C "${SEQ_REPO}" ls-files --others --exclude-standard || true)"

SCRIPT="${OUT}/karabiner_latency_test.ap"
PACK="${OUT}/karabiner_latency_test.sap"
POLICY="${OUT}/action_pack.policy"

cat > "${SCRIPT}" <<EOF
# Generated by tools/gen_action_pack_karabiner_test.sh
# Executes a clean build/test of the Karabiner-Elements latency changes on a remote Mac.

cd /tmp
exec /bin/rm -rf /tmp/karabiner-lat-test /tmp/seq-lat-test
exec /bin/mkdir -p /tmp/karabiner-lat-test /tmp/seq-lat-test

# Stage patch files.
put /tmp/karabiner_latency.patch @$(quote_ap "${OUT}/karabiner_latency.patch")
put /tmp/seq_latency.patch @$(quote_ap "${OUT}/seq_latency.patch")

# Clone from existing local repos on the receiver.
# Uses \$HOME expansion (handled by the action-pack server, not a shell).
exec /usr/bin/git clone --recursive --shared '\$HOME/repos/pqrs-org/Karabiner-Elements' /tmp/karabiner-lat-test
exec /usr/bin/git clone --recursive --shared '\$HOME/code/seq' /tmp/seq-lat-test

# Pin to the sender's base commits for deterministic patch application.
cd /tmp/karabiner-lat-test
exec /usr/bin/git checkout -f ${KAR_HEAD}

cd /tmp/seq-lat-test
exec /usr/bin/git checkout -f ${SEQ_HEAD}

# Apply tracked-file patches.
cd /tmp/karabiner-lat-test
exec /usr/bin/git apply /tmp/karabiner_latency.patch

cd /tmp/seq-lat-test
exec /usr/bin/git apply /tmp/seq_latency.patch
EOF

# Embed untracked files as explicit writes (needed for new headers/tests).
if [ -n "${KAR_UNTRACKED}" ]; then
  echo "" >> "${SCRIPT}"
  echo "# Karabiner untracked files" >> "${SCRIPT}"
  while IFS= read -r f; do
    [ -z "${f}" ] && continue
    dest="/tmp/karabiner-lat-test/${f}"
    src="${KAR_ROOT}/${f}"
    echo "put $(quote_ap "${dest}") @$(quote_ap "${src}")" >> "${SCRIPT}"
  done <<< "${KAR_UNTRACKED}"
fi

if [ -n "${SEQ_UNTRACKED}" ]; then
  echo "" >> "${SCRIPT}"
  echo "# Seq untracked files" >> "${SCRIPT}"
  while IFS= read -r f; do
    [ -z "${f}" ] && continue
    dest="/tmp/seq-lat-test/${f}"
    src="${SEQ_REPO}/${f}"
    echo "put $(quote_ap "${dest}") @$(quote_ap "${src}")" >> "${SCRIPT}"
  done <<< "${SEQ_UNTRACKED}"
fi

cat >> "${SCRIPT}" <<'EOF'

# Build and run tests (no install/deploy, no touching system Karabiner).
cd /tmp/karabiner-lat-test
exec /usr/bin/git status --porcelain
exec /usr/bin/git submodule update --init --recursive
exec /usr/bin/make -C tests -j4
exec /usr/bin/make -C src/core/CoreService -j4
exec /usr/bin/make -C src/core/console_user_server -j4

# Build seq (ensures the companion side still compiles).
cd /tmp/seq-lat-test
exec /bin/bash ./cli/cpp/run.sh build
EOF

echo "Wrote ${SCRIPT}"

cat > "${POLICY}" <<EOF
# key_id-scoped allowlist for action-pack execution.
# Use with: seq daemon --action-pack-policy ${POLICY}
${KEY_ID} cmd=/usr/bin/git cmd=/usr/bin/make cmd=/bin/rm cmd=/bin/mkdir cmd=/bin/bash cmd=/usr/bin/python3 cmd=/usr/bin/xcodebuild cmd=/usr/bin/xcrun cmd=/usr/bin/clang cmd=/usr/bin/clang++ allow_root_scripts=0 allow_exec_writes=0
EOF
echo "Wrote ${POLICY}"

SEQ_BIN="${SEQ_ROOT}/cli/cpp/out/bin/seq"
if [ ! -x "${SEQ_BIN}" ]; then
  echo "error: missing seq binary at ${SEQ_BIN} (run: ./cli/cpp/run.sh build)" >&2
  exit 1
fi

echo "Packing -> ${PACK}"
"${SEQ_BIN}" action-pack pack "${SCRIPT}" --out "${PACK}" --id "${KEY_ID}" --ttl-ms "${TTL_MS}"

cat <<EOF

Simpler flow:
1) Pair once from the sender:
   seq action-pack pair buildmac buildmac:5011 --id ${KEY_ID}
   (optional automation: add `--ssh buildmac` to run setup via tailscale ssh)

2) Run the remote test from the sender:
   seq action-pack karabiner-test buildmac --id ${KEY_ID}

Artifacts:
- Script: ${SCRIPT}
- Pack:   ${PACK}
- Policy: ${POLICY}
EOF
